<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>lark</string>
	</array>
	<key>name</key>
	<string>Lark grammar</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(\?|!)?(\b(?:\w|\s|[\-_0-9])+\b)((\.)(\d+))?\s*(:)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.other.lark</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.lark</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.priority.lark</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.lark</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.definition.lark</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\n)</string>
			<key>endCaptures</key>
			<dict></dict>
			<key>name</key>
			<string>meta.syntax-rule.lark</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#subrules</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(\|)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.alternative.lark</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\n)</string>
			<key>endCaptures</key>
			<dict></dict>
			<key>name</key>
			<string>meta.syntax-rule-alternative.lark</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#subrules</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>%ignore</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.lark</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\n)</string>
			<key>endCaptures</key>
			<dict></dict>
			<key>name</key>
			<string>meta.ignore.lark</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#subrules</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>%import</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.lark</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\n)</string>
			<key>endCaptures</key>
			<dict></dict>
			<key>name</key>
			<string>meta.import.lark</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#subrules</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>//[^\n]*</string>
			<key>end</key>
			<string>(?=\n)</string>
			<key>name</key>
			<string>comment.line.lark</string>
		</dict>
		<key>invalid</key>
		<dict>
			<key>match</key>
			<string>\(\s*[*:/]\s*\)</string>
			<key>name</key>
			<string>invalid.illegal.lark</string>
		</dict>
		<key>non-terminal</key>
		<dict>
			<key>match</key>
			<string>[a-z_]+</string>
			<key>name</key>
			<string>variable.other.non-terminal.lark</string>
		</dict>
		<key>terminal</key>
		<dict>
			<key>match</key>
			<string>[A-Z_]+</string>
			<key>name</key>
			<string>variable.other.terminal.lark</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#operator-literal-range</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-alternative</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-arrow</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-zero-or-more</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-one-or-more</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-optional</string>
				</dict>
			</array>
		</dict>
		<key>operator-literal-range</key>
		<dict>
			<key>match</key>
			<string>\.\.</string>
			<key>name</key>
			<string>keyword.operator.range.lark</string>
		</dict>
		<key>operator-alternative</key>
		<dict>
			<key>match</key>
			<string>\|</string>
			<key>name</key>
			<string>keyword.operator.alternative.lark</string>
		</dict>
		<key>operator-arrow</key>
		<dict>
			<key>match</key>
			<string>-&gt;</string>
			<key>name</key>
			<string>keyword.operator.alias.lark</string>
		</dict>
		<key>operator-zero-or-more</key>
		<dict>
			<key>match</key>
			<string>\*</string>
			<key>name</key>
			<string>keyword.operator.zero-or-more.lark</string>
		</dict>
		<key>operator-one-or-more</key>
		<dict>
			<key>match</key>
			<string>\+</string>
			<key>name</key>
			<string>keyword.operator.one-or-more.lark</string>
		</dict>
		<key>operator-optional</key>
		<dict>
			<key>match</key>
			<string>\?</string>
			<key>name</key>
			<string>keyword.operator.optional.lark</string>
		</dict>
		<key>group</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.group.begin.lark</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.group.end.lark</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#subrules</string>
				</dict>
			</array>
		</dict>
		<key>optional-group</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.optional.begin.lark</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.optional.end.lark</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#subrules</string>
				</dict>
			</array>
		</dict>
		<key>repetition-numbered</key>
		<dict>
			<key>match</key>
			<string>(~)\s*(\d+)\s*((\.\.)\s*(\d+))?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.quantifier.lark</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.lark</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.quantifier.lark</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.lark</string>
				</dict>
			</dict>
		</dict>
		<key>regex-string</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\|/)/(?!/)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.quoted.other.lark</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;!\\|/)(/)(?!/)([imslux]*)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.other.lark</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.regexp-option.lark</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.regexp.lark</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.regexp.python</string>
				</dict>
			</array>
		</dict>
		<key>single-quote-string</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(?:\\\\)*(')</string>
			<key>end</key>
			<string>(?&lt;!\\)(?:\\\\)*(')(i?)</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.regexp-option.lark</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.lark</string>
		</dict>
		<key>double-quote-string</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(?:\\\\)*(")</string>
			<key>end</key>
			<string>(?&lt;!\\)(?:\\\\)*(")(i?)</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.regexp-option.lark</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.lark</string>
		</dict>
		<key>subrules</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#optional-group</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#group</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#repetition-numbered</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#non-terminal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#terminal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single-quote-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double-quote-string</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lark</string>
	<key>uuid</key>
	<string>600B8144-8839-497F-B5A9-A130CAC61159</string>
</dict>
</plist>
