<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>g</string>
		<string>lark</string>
		<string>lr</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\(\*</string>
	<key>foldingStopMarker</key>
	<string>\*\)</string>
	<key>keyEquivalent</key>
	<string>^~E</string>
	<key>name</key>
	<string>Lark grammar</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(\?|!)?(\b(?:\w|\s|[\-_0-9.])+\b)\s*(:)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.other.ebnf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ebnf</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.definition.ebnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\n)</string>
			<key>endCaptures</key>
			<dict></dict>
			<key>name</key>
			<string>meta.syntax-rule.ebnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#subrules</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(\|)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.alternative.ebnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\n)</string>
			<key>endCaptures</key>
			<dict></dict>
			<key>name</key>
			<string>meta.syntax-rule-alternative.ebnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#subrules</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>%ignore</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ebnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\n)</string>
			<key>endCaptures</key>
			<dict></dict>
			<key>name</key>
			<string>meta.ignore.ebnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#subrules</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>%import</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.ebnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\n)</string>
			<key>endCaptures</key>
			<dict></dict>
			<key>name</key>
			<string>meta.import.ebnf</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#subrules</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>//[^\n]*</string>
			<key>end</key>
			<string>(?=\n)</string>
			<key>name</key>
			<string>comment.line.ebnf</string>
		</dict>
		<key>double-quote-string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ebnf</string>
		</dict>
		<key>group</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.group.begin.ebnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.group.end.ebnf</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#subrules</string>
				</dict>
			</array>
		</dict>
		<key>invalid</key>
		<dict>
			<key>match</key>
			<string>\(\s*[*:/]\s*\)</string>
			<key>name</key>
			<string>invalid.illegal.ebnf</string>
		</dict>
		<key>non-terminal</key>
		<dict>
			<key>match</key>
			<string>\w[\w\-_0-9]*\w</string>
			<key>name</key>
			<string>variable.other.non-terminal.ebnf</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#operator-alternative</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-concatenation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-arrow</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-exception</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-zero-or-more</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-one-or-more</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator-optional</string>
				</dict>
			</array>
		</dict>
		<key>operator-alternative</key>
		<dict>
			<key>match</key>
			<string>\|</string>
			<key>name</key>
			<string>keyword.operator.alternative.ebnf</string>
		</dict>
		<key>operator-concatenation</key>
		<dict>
			<key>match</key>
			<string>,</string>
			<key>name</key>
			<string>keyword.operator.concatenation.ebnf</string>
		</dict>
		<key>operator-arrow</key>
		<dict>
			<key>match</key>
			<string>-&gt;</string>
			<key>name</key>
			<string>keyword.operator.alias.ebnf</string>
		</dict>
		<key>operator-exception</key>
		<dict>
			<key>match</key>
			<string>-</string>
			<key>name</key>
			<string>keyword.operator.exception.ebnf</string>
		</dict>
		<key>operator-zero-or-more</key>
		<dict>
			<key>match</key>
			<string>\*</string>
			<key>name</key>
			<string>keyword.operator.zero-or-more.ebnf</string>
		</dict>
		<key>operator-one-or-more</key>
		<dict>
			<key>match</key>
			<string>\+</string>
			<key>name</key>
			<string>keyword.operator.one-or-more.ebnf</string>
		</dict>
		<key>operator-optional</key>
		<dict>
			<key>match</key>
			<string>\?</string>
			<key>name</key>
			<string>keyword.operator.optional.ebnf</string>
		</dict>
		<key>optional</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.optional.begin.ebnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.optional.end.ebnf</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#subrules</string>
				</dict>
			</array>
		</dict>
		<key>repetition</key>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.repetition.begin.ebnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.repetition.end.ebnf</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#subrules</string>
				</dict>
			</array>
		</dict>
		<key>repetition-numbered</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.ebnf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.repetition.ebnf</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\d+)\s*(\*)</string>
		</dict>
		<key>single-quote-string</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.ebnf</string>
		</dict>
		<key>regex-string</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\|/)/(?!/)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.ebnf</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;!\\|/)(/)(?!/)([cegimosx]*)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.single.ebnf</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.regexp-option.ebnf</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.regexp.lark</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.regexp.python</string>
				</dict>
			</array>
		</dict>
		<key>subrules</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#optional</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#repetition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#group</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#repetition-numbered</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#non-terminal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single-quote-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double-quote-string</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ebnf</string>
	<key>uuid</key>
	<string>D9954069-097B-4361-818D-EF4986D442E7</string>
</dict>
</plist>
